#spring.application.name=calculator-api
server:
  servlet:
    context-path: /calculator-api
  port: 8082
spring:
  application:
    name: calculator-api
  datasource:
    url: jdbc:h2:mem:calculatordb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: info

