server:
  servlet:
    context-path: /tranferbank-api
  port: 8080
spring:
  application:
    name: tranferbank-api
  datasource:
    url: jdbc:h2:mem:transferdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect